import { CalendarEventObject } from '../src/types/dav-parser';

export const simpleIcs = `BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
SUMMARY:Access-A-Ride Pickup
DTSTART;TZID=America/New_York:20130802T103400
DTEND;TZID=America/New_York:20130802T110400
LOCATION:1000 Broadway Ave Brooklyn
DESCRIPTION: Access-A-Ride trip to 900 Jay St. Brooklyn
STATUS:CONFIRMED
SEQUENCE:3
BEGIN:VALARM
TRIGGER:-PT10M
DESCRIPTION:Pickup Reminder
ACTION:DISPLAY
END:VALARM
END:VEVENT
BEGIN:VEVENT
SUMMARY:Access-A-Ride Pickup
DTSTART;TZID=America/New_York:20130802T200000
DTEND;TZID=America/New_York:20130802T203000
LOCATION:900 Jay St. Brooklyn
DESCRIPTION: Access-A-Ride trip to 1000 Broadway Ave. Brooklyn
STATUS:CONFIRMED
SEQUENCE:3
BEGIN:VALARM
TRIGGER:-PT10M
DESCRIPTION:Pickup Reminder
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR`;

export const customPropertiesIcs = `BEGIN:VCALENDAR
BEGIN:VEVENT
UID:0ff6c544-cd94-4611-82ed-ecc04d8a686f
TRANSP:OPAQUE
DTSTART;TZID=Europe/Paris:20210315T100000
DTEND;TZID=Europe/Paris:20210315T110000
CLASS:PUBLIC
X-OPENPAAS-VIDEOCONFERENCE:https://jitsi.linagora.com/calendar
SUMMARY:Notification component grooming
LOCATION:https://jitsi.linagora.com/calendar
DESCRIPTION:
ORGANIZER;CN=Renaud BOYER;SCHEDULE-STATUS=1.1:mailto:rboyer@linagora.com
DTSTAMP:20210314T212006Z
ATTENDEE;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;ROLE=REQ-PARTICIPANT;CUTYPE=INDIVI
 DUAL;CN=Huy TA QUOC:mailto:htquoc@linagora.com
ATTENDEE;PARTSTAT=ACCEPTED;RSVP=TRUE;ROLE=REQ-PARTICIPANT;CUTYPE=INDIVIDUAL
 ;CN=Khaled FERJANI:mailto:kferjani@linagora.com
ATTENDEE;PARTSTAT=ACCEPTED;RSVP=FALSE;ROLE=CHAIR;CUTYPE=INDIVIDUAL;CN=Renau
 d BOYER:mailto:rboyer@linagora.com
SEQUENCE:1
END:VEVENT
END:VCALENDAR
`;

export const recurringEventIcs = `BEGIN:VCALENDAR
BEGIN:VEVENT
UID:34b68b1b-8463-4610-8098-0c937bfdecba
TRANSP:OPAQUE
DTSTART;TZID=Asia/Ho_Chi_Minh:20201026T153000
DTEND;TZID=Asia/Ho_Chi_Minh:20201026T160000
CLASS:PUBLIC
X-OPENPAAS-VIDEOCONFERENCE:
SUMMARY:Daily Meeting - Team Calendar/Contacts
DESCRIPTION:https://jitsi.linagora.com/calendar
RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR
ORGANIZER;CN=Huy TA QUOC:mailto:htquoc@linagora.com
DTSTAMP:20201026T084834Z
SEQUENCE:6
LOCATION:https://jitsi.linagora.com/calendar
ATTENDEE;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;ROLE=REQ-PARTICIPANT;CUTYPE=INDIVI
 DUAL;CN=Renaud BOYER:mailto:rboyer@linagora.com
ATTENDEE;PARTSTAT=ACCEPTED;RSVP=TRUE;ROLE=REQ-PARTICIPANT;CUTYPE=INDIVIDUAL
 ;CN=Khaled FERJANI:mailto:kferjani@linagora.com
ATTENDEE;PARTSTAT=ACCEPTED;RSVP=TRUE;ROLE=REQ-PARTICIPANT;CUTYPE=INDIVIDUAL
 ;CN=Lilya THEBTI:mailto:lthebti@linagora.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;ROLE=REQ-PARTICIPANT;CUTYPE=INDIVI
 DUAL;CN=Ba Son PHAM:mailto:bspham@linagora.com
ATTENDEE;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;ROLE=REQ-PARTICIPANT;CUTYPE=INDIVI
 DUAL;CN=Asma AYARI:mailto:aayari@linagora.com
ATTENDEE;PARTSTAT=ACCEPTED;RSVP=FALSE;ROLE=CHAIR;CUTYPE=INDIVIDUAL;CN=Huy T
 A QUOC:mailto:htquoc@linagora.com
BEGIN:VALARM
TRIGGER:-PT15M
ACTION:EMAIL
ATTENDEE:mailto:kferjani@linagora.com
SUMMARY:Daily Meeting - Team Calendar/Contacts
DESCRIPTION:This is an automatic alarm sent by OpenPaas\\nThe event Daily M
 eeting - Team Calendar/Contacts will start 3 months ago\\nstart: Mon Oct 2
 6 2020 15:30:00 GMT+0700 \\nend: Mon Oct 26 2020 16:00:00 GMT+0700 \\nloca
 tion: https://jitsi.linagora.com/calendar \\nclass: PUBLIC \\n
END:VALARM
END:VEVENT
END:VCALENDAR
`;

export const sabreIcs = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 4.1.3//EN
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Africa/Lagos
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
TZNAME:WAT
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
UID:d4954f7e-2cab-47dc-bc77-2420b3594a3b
TRANSP:OPAQUE
DTSTART;TZID=UTC:20201127T140000Z
DTEND;TZID=UTC:20201127T143000Z
CLASS:PUBLIC
X-OPENPAAS-VIDEOCONFERENCE:
SUMMARY:R
ORGANIZER;CN=John0 Doe0:mailto:user0@open-paas.org
ATTENDEE;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;ROLE=REQ-PARTICIPANT;CUTYPE=INDIVI
  DUAL:mailto:user1@open-paas.org
ATTENDEE;PARTSTAT=TENTATIVE;RSVP=TRUE;ROLE=REQ-PARTICIPANT;CUTYPE=RESOURCE;
  CN=ball:mailto:5fbb8a4fb77afc7fc0edc6c1@open-paas.org
ATTENDEE;PARTSTAT=ACCEPTED;RSVP=FALSE;ROLE=CHAIR;CUTYPE=INDIVIDUAL:mailto:u
  ser0@open-paas.org
DTSTAMP:20201123T114503Z
SEQUENCE:0
END:VEVENT
END:VCALENDAR
`;


export const testEventObject: CalendarEventObject = {
  id: '123456',
  title: 'test',
  start: '2021-03-15T10:00:00',
  end: '2021-03-15T11:00:00',
  allDay: false,
  description: 'simple description',
  location: 'some location',
  duration: {
    hours: 1,
  },
  extendedProps: {},
};
